version: "3.3"

services:

  flapjack_api:
    container_name: api
    restart: always
    build: .
    volumes:
      - .:/var/app/flap
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000

  db:
    container_name: db
    restart: always
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: guillermo
      POSTGRES_PASSWORD: 123456
    volumes:
      - ../pgdata:/var/pg/data