version: "3.3"

services:
  flapjack_api:
    container_name: api
    restart: always
    build: .
    volumes:
      - .:/var/app/flap
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    #command: gunicorn --certfile=cert/fullchain.pem --keyfile=cert/privkey.pem flapjack_api.wsgi:application
    #command: gunicorn flapjack_api.wsgi
    command: python manage.py runserver 0.0.0.0:8000

  db:
    container_name: db
    restart: always
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: registry
      POSTGRES_USER: guillermo
      POSTGRES_PASSWORD: 123456
    volumes:
      - db:/var/pg/data

  redis:
    image: redis
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 5m
      timeout: 30s
      retries: 30

volumes:
  redis:
  db:
