version: "3.3"

services:
  flapjack_api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn flapjack_api.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:12.1
    volumes:
      - db:/var/pg/data
    env_file:
      - ./.env.prod.db

  redis:
    image: redis
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - flapjack_api
      - daphne

  daphne:
    container_name: daphne
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: daphne -b 0.0.0.0 -p 7000 flapjack_api.asgi:application
    expose:
      - 7000
    depends_on:
      - redis
    env_file:
      - ./.env.prod

volumes:
  redis:
  db:
